<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Publish settings -->
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <!-- Base version -->
    <BaseVersion Condition="'$(GITHUB_REF_NAME)' == ''">0.0.1</BaseVersion>
    <BaseVersion Condition="'$(GITHUB_REF_NAME)' != ''">$([System.String]::Copy('$(GITHUB_REF_NAME)').TrimStart('v'))</BaseVersion>

    <!-- Product / NuGet version -->
    <Version>$(BaseVersion)</Version>

    <!-- Informational version with commit SHA -->
    <InformationalVersion>$([System.String]::Copy('$(BaseVersion)'))+$(GITHUB_SHA)</InformationalVersion>

    <!-- Extract numeric part safely -->
    <NumericVersion>$([System.Text.RegularExpressions.Regex]::Match('$(BaseVersion)', '^\d+\.\d+\.\d+').Value)</NumericVersion>

    <!-- Assembly / File version -->
    <AssemblyVersion>$(NumericVersion).0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Base configuration, included in build and publish output. --> 
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" /> 

    <!-- Development-specific override: only include if the file actually exists. Will not be included in publish output. -->
    <Content Include="appsettings.Development.json" Condition="Exists('appsettings.Development.json')" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
